backend:
  name: github
  repo: emmanuelgratuze/gueiv-directory-frontend
  branch: content
media_folder: assets/uploads
public_folder: assets
collections:
  - label: "Brand"
    name: "brand"
    folder: "contents/brands"
    extension: json
    format: json
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Criteria", name: "criteria", widget: "relation", collection: "brand", displayFields: "title"}
  - label: "Criterion"
    name: "criterion"
    folder: "contents/criteria"
    extension: json
    format: json
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}